

###
POST localhost:8080/v1/users/login
Content-Type: application/json


{
  "username": "XieShurui",
  "password": "123456"
}

###
POST localhost:8080/v1/users/reg
Content-Type: application/json

{
  "username": "CaiXunkun",
  "password": "123456",
  "nickname": "ikun"
}

###
GET localhost:8080/v1/contents/1/management?type=1
Content-Type: application/json

{
  "username": "Jack",
  "password": "123456"
}